version: '3.3'
services:
    cloudflare-ddns:
        container_name: cloudflare_ddns
        image: oznu/cloudflare-ddns
        restart: always
        environment:
            - API_KEY=XXXXXXXXXXXXXXXXXXXX
            - ZONE=example.com
            - SUBDOMAIN=test
    homeassistant:
      container_name: homeassistant
      image: "ghcr.io/home-assistant/home-assistant:stable"
      restart: always
      network_mode: host
      volumes:
        - /home/apps/homeasisstant:/config
        - /etc/localtime:/etc/localtime:ro
      privileged: true
    homepage:
      container_name: homepage
      image: ghcr.io/benphelps/homepage:latest
      restart: always
      ports:
        - 126:3000
      volumes:
        - /home/apps/homepage:/app/config # Make sure your local config directory exists
        - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    vaultwarden:
      container_name: vaultwarden
      image: 'vaultwarden/server:latest'
      restart: always
      ports:
        - '125:80'
      volumes:
        - /home/apps/vaultwarden/vw-data/:/data/
