version: '3.3'
services:
#####################################################################################################
    cloudflare-ddns:
      container_name: cloudflare_ddns
      image: oznu/cloudflare-ddns
      restart: always
      networks:
        docker_net1:
          ipv4_address: 10.228.210.4
      environment:
        - API_KEY=XXX
        - ZONE=skaldor.uk
      # - SUBDOMAIN=test #uncomment to use sub domain
      deploy:
        resources:
          limits:
            memory: 30M
          reservations:
            memory: 6M
#####################################################################################################
    homeassistant:
      container_name: homeassistant
      image: "ghcr.io/home-assistant/home-assistant:stable"
      restart: always
      network_mode: host #Port:8123
      volumes:
        - /home/apps/homeassistant:/config
        - /etc/localtime:/etc/localtime:ro
      deploy:
        resources:
          limits:
            memory: 1G
          reservations:
            memory: 250M
      privileged: true
#####################################################################################################
    homepage:
      container_name: homepage
      image: ghcr.io/benphelps/homepage:latest
      restart: always
      networks:
        docker_net1:
          ipv4_address: 10.228.210.3 #Port:3000
      volumes:
        - /home/apps/homepage:/app/config # Make sure your local config directory exists
        - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
#####################################################################################################
    vaultwarden:
      container_name: vaultwarden
      image: 'vaultwarden/server:latest'
      restart: always
      networks:
        docker_net1:
          ipv4_address: 10.228.210.2 #Port:80
      volumes:
        - /home/apps/vaultwarden/vw-data/:/data/
#####################################################################################################
    nginx_proxy_manager:
      container_name: nginx_reverse_proxy
      image: 'jc21/nginx-proxy-manager:latest'
      restart: always
      networks:
        docker_net1:
          ipv4_address: 10.228.210.1
      ports:
        # These ports are in format <host-port>:<container-port>
        - 80:80 # Public HTTP Port
        - 443:443 # Public HTTPS Port
        #- 124:81 # Admin Web Port
        # Add any other Stream port you want to expose
        # - 21:21 # FTP
      # Uncomment the next line if you uncomment anything in the section
      # environment:
        # Uncomment this if you want to change the location of
        # the SQLite DB file within the container
        # DB_SQLITE_FILE: "/data/database.sqlite"
        # Uncomment this if IPv6 is not enabled on your host
        # DISABLE_IPV6: 'true'
      volumes:
        - /home/apps/nginx_reverse_proxy/data:/data
        - /home/apps/nginx_reverse_proxy/letsencrypt:/etc/letsencrypt
      deploy:
        resources:
          limits:
            memory: 2G
          reservations:
            memory: 250M

#####################################################################################################
networks:
  docker_net1:
    name: docker_net1
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: "10.228.0.0/16"
          ip_range: "10.228.210.0/24"
          gateway: "10.228.0.10"
