version: '3.3'
services:
    guacamole:
        container_name: guac
        restart: always
        ports:
            - '128:8080'
        volumes:
            - '${PWD}:/config'
        environment:
            - EXTENSIONS=auth-totp
        image: flcontainers/guacamole
