version: '3.3'
services:
  searxng:
    image: searxng/searxng
    container_name: searx_engine
    restart: always
    ports:
      - '127:8080'
    volumes:
      - '${PWD}:/etc/searxng'
    environment:
      - INSTANCE_NAME=surf